RocketPy-Team/RocketPy

rocketpy/Flight.py
rocketpy/Rocket.py

Update Rocket class:
- Some changes in the addFins() function to allow Fin analysis in the flight class
- Inertia details now prints data using .format options
Several changes in Flight class:
- Flight.allInfo () has been separated into 12 other functions, **now we can plot specific graphics more freely**. However, Flight.allInfo () still exists and still works as usual.
- Some changes in what is printed by the functions, numerical and graphic information. Better axis limits for various graphs. Added some prints for the Burn Out Time.
- Added a function capable of estimating the critical speed of fin flutter.
- Added a new attribute: thrustToWeight, it is defined as the ratio between the thrust force of the motor and the weight of the rocket
- Added a function that allows you to export …

Flight.allInfo() has been remodeled!

---

rocketpy/Flight.py
rocketpy/Rocket.py

Since many versions ago (could not map exactly which), the `initialSolution` argument of the **Flight class** stopped working.
The problem occurred since given an initial solution, the rocket may be already out of rail since the first simulation step. This triggered the _out of rail event_ which tried to find out when the rocket left the rail by performing root finding. When no solutions can be found, an exception is raised.

Bugfix: Custom initial solution for Flight class

---

rocketpy/EnvironmentAnalysis.py

Currently, every datetime used and printed/plotted by the `EnvironmentAnalysis` class is in UTC.
Now, the user can specify which timezone he prefers to use. This can be specially useful to display results in a timezone which is easier to understand.

ENH: Environment Analysis - Time Zones

---

docs/notebooks/getting_started.ipynb
docs/notebooks/getting_started_colab.ipynb
rocketpy/Rocket.py

The proposed implementation of Rocket.addFins (#172 ) will cause breaking changes.
The new proposed implementation creates two methods: `Rocket.addTrapezoidalFins` and `Rocket.addEllipticalFins` to avoid breaking changes. Furthermore, it marks `Rocket.addFins` as a future deprecation to be removed in version 2.0.0 (to be discussed).
Work to fix notebooks and docs that mention `addFins` must be worked on to reflect theses changes.

ENH: Refactor Rocket.addFins to avoid breaking changes

---

rocketpy/Flight.py
rocketpy/Rocket.py

`powerOnDrag` and `powerOffDrag` are inverted in the flight class, so the simulation is using `powerOffDrag` while the motor is on an `powerOnDrag` when the motor is off. 
Also, both drag curves are used to set a Function object with `'spline'` interpolation. Sometimes this can cause problems with clustered data archives. Changed it to `'linear'` so it is more compatible.

BUG: Power on and power off drag inverted

---

requirements.txt
rocketpy/EnvironmentAnalysis.py

To serialize and deserialize the class you just need to do as following:
```
In [1]: 
...: from rocketpy.EnvironmentAnalysis import EnvironmentAnalysis
...: from datetime import datetime
...: import matplotlib.pyplot as plt
...: import numpy as np
...: from scipy import stats
In [2]: env_analysis = EnvironmentAnalysis(
...:     start_date=datetime(2002, 6, 15),  # (Year, Month, Day)
...:     end_date=datetime(2021, 6, 30),  # (Year, Month, Day)
...:     start_hour=6,
...:     end_hour=18,
...:     latitude=32.990629,
...:     longitude=-106.976097,
...:     surfaceDataFile="data/weather/spaceport_america_single_level_reanalysis_2002_2021.nc",
...:     pressureLevelDataFile="data/weather/spaceport_america_pressure_levels_reanalysis_2002_2021.nc",
...:     timezone="America/Denver",
...: …
```

Enh: Using jsonpickle to serialize EnvAnal

---

docs/user/requirements.rst
requirements.txt
rocketpy/EnvironmentAnalysis.py
setup.py

I'm fixing a problem regarding the PR #226 tasks list.
Now it's finally possible to save the already-processed data from EnvironmentAnalysis into a .json file and then re-use it to initialize other Environment Analysis objects 
I'm creating this PR only to have theses steps documented in the future, reviewing it is important, but please keep in mind that others PR are coming soon and they will need these implementations already merged

ENH: Refactor Env Analysis .json conversions

---

rocketpy/Flight.py

Using the `initialSolution` argument of the Flight class is quite inconvenient, specially when you retrieve from a previous Flight instance. The argument only supports an array as input.
`Flight` instances can now be used as input to the `initialSolution` argument of the Flight class. 
One option that we have is: should we initialize the solution monitors by copying the data from the Flight instance submited in the `initialSolution` argument? If we do this, the resulting Flight will have trajectory data from both Flights. Is this a convinience or an inconvience?

ENH: Simple Initial Solution

---

rocketpy/Flight.py

The `Flight.postProcess()` method usually takes too many time to run, creating a huge step from 
- Most of the old attributes (e.g. `Flight.x`, `Flight.angleOfAttack`, `Flight.speed`) are now defined by using properties decorators at the Flight class. Therefore they can be accessed without previous running `postProcess()`, meaning that the property object will be evaluated only when it is called.
- I have used cached_properties since memory usage was not a problem at the time, but perhaps in the future it can be modified. This way we guarantee that. Mutating properties can be a particular trick part here, I'm not an expert to explain, but we should be aware errors similar to: …

ENH: Introducing properties in Flight class

---

rocketpy/Rocket.py
tests/test_rocket.py

See #256, which merged to develop.
Merging here to help with EuroC simulations.

ENH: Swept Back Fins for EuroC

---

.github/workflows/publish-to-pypi.yml

Since Travis CI stopped working, automatic publishing of new releases to PyPI stopped working.
A GitHub Action called `Publish New Version to PyPI` will be triggered when a new release is published, building rocketpy and uploading it to PyPI.
Inspiration from: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

REL: Automate Release to PyPI with GitHub Actions

---

rocketpy/Flight.py
rocketpy/tools.py

Python 3.6 and 3.7 does not include `functools.cached_property`, which is currently being used in the develop branch causing errors.
Since RocketPy does support Python 3.6+ according to our [docs](https://docs.rocketpy.org/en/latest/user/requirements.html#python-version), this needs to be fixed.
@Gui-FernandesBR had proposed a solution for this issue in #279, however, I was not comfortable with it since it made use of `functools.lru_cache`. It is my understanding that such implementation uses much more memory since it stores a copy of the class instance to make sure that the input argument `self` …

Fix: Cached Property support for Python 3.6 and 3.7

---

rocketpy/Environment.py
rocketpy/prints/environment_prints.py

---
This PR is related to the `1st PR: moving prints from Environment.py to environment_prints.py` check box in https://github.com/RocketPy-Team/RocketPy/pull/287

ENH: Moved Environment prints to environment_prints.py

---

rocketpy/Flight.py

I cannot easily differentiate one flight object from other.
New argument and attribute "name" added to Flight class, allowing if to easily label/name your object. It was inspired in the recent AeroSurfaces implementation. This will help a lot on compare plots functions.
Could apply to other classes as well, if evrybody thinks

ENH: adding name as a karg in Flight class

---

rocketpy/Flight.py
tests/test_flight.py

Flight attribute `bearing` currently faces some problems:
1. takes a lot of time to be calculated
2. is printing a list where it should be printing
3. bugs in some cases due to non continuous function
All the three problems solved with simple code lines
I took this implementation from: https://github.com/RocketPy-Team/RocketPy/commit/62e21722a38b77931afa9e0f5fb61c50d1255b99
Credits to Mr. @giovaniceotto

Fix: Flight Bearing

---

tests/test_rocket.py

In tests where we checked static margin values we were calling the `rocket.staticMargin(-1)` and `rocket.centerOfMass(-1)` when trying to get the final values of these objects.
This actually returns the value of that Function for a input value of `-1`. The correct way to get the final values is with `rocket.staticMargin(np.inf)` and `rocket.centerOfMass(np.inf)`

TST: Fix static margin related tests

---

rocketpy/motors/LiquidMotor.py

`LiquidMotor` class lacks inertia tensor implementation and does not have complete docstrings.
The `LiquidMotor` class now calculates the inertia tensor from each of its tanks inertia. Furthermore, docstrings were added and updated when necessary, along with minor fixes in `__init__`.

ENH: Liquid Motors Updates

---

README.md

Docs page cannot load two images of our README.md file as they have bad reference.
Images are now referred to their raw content, and therefore the docs page should be restored.
This solves the #204 issue.
It is true that more improvements to the README.md files can be done, but this PR aims to only solve the proposed related issue.

MAINT: use raw.githubusercontent address in readme

---

rocketpy/Flight.py

When working on #290 I found that the `Flight.plotPressureSignals` method did not work. This was just because the `__calculate_pressure_signal` method was not being called. Furthermore, when using `"StandardAtmosphere"` the `Pressure at Rocket's Altitude` plot raised an error. This error comes from calling `Environment.pressure` with an array as such: 
Using a list instead works fine:
I am pretty sure that a Function object should be able to receive an np.array so I think this not working as intended.
One more thing, looking at how the pressure Function is calculated for `StandardAtmosphere`. Lines 2832 and 2833 are incoherent. I don't know much about pressure profiles though, so I might be wrong. Maybe @Gui-FernandesBR or @giovaniceotto know more.
The only thing changed currently in this …

BUG: Flight.plotPressureSignals and "StandardAtmosphere" environment pressure calculation

---

rocketpy/plots/compare/compare_flights.py
rocketpy/plots/rocket_plots.py
tests/conftest.py
tests/test_environment.py
tests/test_plots.py

We need unit tests to finish #287 development.
Tests were added, the coverage reported was generated and is printed below:
Obs.: The number 14, highlighted, should be, actually, 0.
To reproduce the report, just run: 
`coverage run --module pytest --runslow`
`coverage html`
@MateusStano , please read the commits descriptions 1 by 1 in order to understand what I've done.
Basically, a couple of MAINT were needed to optimize the tests, mainly, avoiding repetitions.
I am adding only two new tests, and I think everything is already being accomplished for now.
We can separate these two functions …

TST: new plots tests

---

.github/workflows/test_pytest.yaml
docs/user/requirements.rst
rocketpy/EnvironmentAnalysis.py
setup.py

1. RocketPy fails to install when using Python 3.7 on Windows, since the `timezonefinder` package does not support Python 3.7 anymore. See #314.
2. The `timezonefinder` package is rarely used and not required for any major RocketPy functionality. It is currently a required package inspite of this. And to make things worse, it requires a download larger than 40 MB.
The `timezonefinder` is made an optional requirement. By default, when installing RocketPy, it will not be installed and thus RocketPy will remain compatible with Python 3.7. The total downloads needed to install RocketPy will be reduced by …

ENH: Make timezonefinder an optional dependency

---

rocketpy/Flight.py
rocketpy/utilities.py
tests/conftest.py
tests/test_utilities.py

Fin Flutter Analysis is polluting the Flight.py file!!!
- A new function `fin_flutter_analysis` was created inside. Some workarounds to handle with divisions by zero but everything is working as expected!
- New test to cover the flutter analysis
Adding an example to the utilities notebook would be interesting, but I do not see reasons for doing it right now at this PR. It is better to give an example after we get near to the next release.

MAINT: move flutter analysis into utilities submodule

---

rocketpy/AeroSurfaces.py
rocketpy/Environment.py
rocketpy/EnvironmentAnalysis.py
rocketpy/Parachute.py
rocketpy/plots/compare/compare.py
rocketpy/plots/compare/compare_flights.py
rocketpy/plots/environment_plots.py
tests/fixtures/acceptance/EPFL_Bella_Lui/bella_lui_flight_sim.py
tests/fixtures/acceptance/NDRT_2020/ndrt_2020_flight_sim.py
tests/test_environment.py

The very same behavior, the very same results, but now there is no `plt.plot(...` inside the Enrivonment class
This PR could be seen as an extension of #296

MAINT: move last plots from Environment class

---

rocketpy/AeroSurfaces.py

Only a few types of nosecones were supported with Cp calculations.
Elliptical and tangent types of nosecone added following the theory on THE DESCRIPTIVE GEOMETRY OF NOSE CONES, 1996, Gary A. Crowell Sr.
Now we have the value "k" for these nosecone in order to be able to calculate its center of pressure. 
Also checked that Von Karman and parabolic types are covered on the else statement. k = 0.5
Therefore, the documentation was update stating that the code support elliptical, parabolic, von Karman and tangent nosecones. 

ENH: New nosecone types added.

---

rocketpy/EnvironmentAnalysis.py

The usage of the import statement of the module `timezonefinder` was incorrect, raising an error only when `pytest --runslow` is run.
This means that all branches derived from `beta/v1.0.0` did not pass the runslow tests.
The import was corrected, now all tests of `pytest --runslow` run successfully.

FIX: Correct timezonefinder import.

---

rocketpy/Function.py
tests/test_function.py

There is a problem in the Dispersion class when it comes to saving Function objects in the `.txt` files. This is a special problem in the `.disp_inputs.txt` files, since the values of `powerOffDrag`, `powerOnDrag` and others are received as Functions.
What happens in these cases is, when saving in the `.txt` file we simply pass a dictionary, which contains the info of the simulation inputs, into the `write` function. The interaction between the `write` function and the `Function` class is so that what gets saved in the file is the `Function` `__repr__`. For example:
```python
{ ... "powerOffDrag": Function from R1 to R1 : (Scalar) → (Scalar), ... }
```
Further on, in the dispersion class, there is an attribute called `inputs_log` that generates, from the input file, a list in which each …

ENH: add " ' " to Function __repr__

---

docs/notebooks/topography_usage.ipynb
rocketpy/Environment.py
rocketpy/Flight.py
rocketpy/prints/environment_prints.py
tests/test_environment.py
tests/test_flight.py

Some of the arguments in the `Environment` class are being saved on `self` with a different name, e.g. the argument `railLength` is saved with `self.rL = railLength`.
If `getattr` is run with the name of the arguments it will not be able to get the `railLength` value inputted. This is a huge problem for the `Dispersion` class, since it is heavilydependent in `getattr`.
The following attributes were changed:
- `self.rL` --> `self.railLenght`
- `self.lat` --> `self.latitude`
- `self.lon` --> `self.longitude`
- created `self.datetime_date`, which is what `self.date` was before these changes. Meaning, it is the argument `date` transformed into a datetime object with the inputted timezone
- made `self.date` save the exact argument inputted in `date`
`self.g` is also a problem here but it is …

ENH: Environment changes for Dispersion

---

rocketpy/Flight.py

- ### Continuing from #343 
- Seems like not all changes required to fix this issue were made. Probably I made some mistakes with git somewhere in the way of importing these changes from the dispersion to a new branch
Anyway, need your review again @giovaniceotto

BUG: Parachute lag warning when lag is 0 #2

---

rocketpy/Flight.py
rocketpy/Function.py
tests/conftest.py
tests/test_function.py

The Function class currently lacks basic methods of comparison and identity map.
The comparison works in a very similar way to comparing arrays in numpy. When this comparison cannot be performed, an error is raised. The identity map is basically an implementation of the function $f(x) = x$ that follows the same discretization as the instance.

Function Comparison and Identity Map

---

rocketpy/Environment.py

@MateusStano recently caught an inconsistency with the geopotential <=> geometric altitudes in the Environment Class.
I hereby confirm that is currently a BUG and the code has not been working properly so far.
I verified every equation in the Standard Atmosphere model, comparing each of them with the ISO 2533 available online.
All the inconsistencies were removed.
A few comments were provided to warn users of model limitations.
* It is not hard to find the ISO-2533 online, just google it including "pdf". However, it seems that it was update in 2021 but only a paid version can be found so …

BUG: fix standard atmosphere

---

docs/user/requirements.rst
requirements.txt
setup.py

The requirements for netcdf4 dependency is a bit more complex than what would be ideal. This has been a problem since the BUG #205 was reported.
Everything is easier with the newest version of netcdf4, which may work without error all environments, including google colab.
- It is sad that this PR isn't going to the master branch directly, but let's be patient and wait until the v1 gets finally merged into master
- This PR should wait for the #365 to be merged into beta/v1.0.0
- This should finally fix the BUG mentioned above (#205 )

MAINT: upgrade netcdf4 requirement

---

rocketpy/Function.py

The `funcify_method` decorator from `Function` did not update the titles for methods that returned `Function` instances.
This issue was fixed by updating the `reset` method from `Function` with a call to `setTitle`.

FIX: funcify titles - pt1

---

README.md
rocketpy/Environment.py
rocketpy/prints/environment_prints.py

Documentation was out of date regarding features of `v1.0.0a1`.
Readme.md was updated with essential info regarding `HybridMotor` and `LiquidMotor`.

DOC: update README.md with new features of v1.0.0a1.

---

rocketpy/Flight.py

The calculation for the effective rail length was wrong ever since the Rail Buttons and Distance x Positions PRs were merged.
This causes serious calculations errors in the out-of-rail speed values

BUG: Wrong Effective Rail

---

rocketpy/Flight.py
rocketpy/prints/flight_prints.py
rocketpy/tools.py

If a flight simulation happens to have a parachute whose trigger generates an acceleration bigger than the acceleration generated by the motor, only the acceleration due to the parachute trigger will be printed out in the `info` and `all_info` methods
Now, a print is added in cases where the motor acceleration is not what caused the highest acceleration:
Note that when the maximum acceleration **is** caused by the motor, the extra printed lines are not added
I also tried adding a print for the acceleration at the `open_time` of the parachute, but the acceleration at that time is not the max acceleration caused by the parachute opening. The max only happens a bit of time after the event and can not easily be determined.

ENH: Add Maximum Acceleration During Burn Print

---

tests/test_environment_analysis.py

You get 60 matplotlib windows when running "pytest --runslow"
Nice catch by @phmbressan , the code was missing one patching decorator.
The largest PR ever 😁

TST: env analysis tests on slow option opens matplotlib (solve #380) 

---

rocketpy/EnvironmentAnalysis.py

It says AGL, but it is actually ASL. 
Environment Analysis no longer suffers from ASL/AGL label mistakes
It only changes the labels of some charts. Numerical results are kept the same

BUG: env analysis altitudes ASL mistake (solve #371)

---

docs/technical/aerodynamics/elliptical_fins.rst
rocketpy/AeroSurface.py

An `EllipticalFins` object could be defined if it had the span smaller than the rocket radius, as stated in Issue #390. This was due to the expression used to evaluate the `roll_damping_interference_factor` that wasn't defined at that domain.
With a whole bunch of calculus, I got the correct expressions for when the span is bigger to the rocket radius and for when the span is equal to the radius. 
The new expressions have been added to the documentation and added to the code accordingly

BUG: EllipticalFins Roll Damping Factor Calculation

---

rocketpy/AeroSurface.py
rocketpy/plots/aero_surface_plots.py
rocketpy/prints/aero_surface_prints.py

You give an airfoil curve as input, but RocketPy do not let you to check if the curve is correct.
A few more plots or prints were added to improve the visualization of airfoil data when it is used.
This closes #144 
Easy to review.

ENH: airfoil outputs (resolve #144)

---

rocketpy/Rocket.py
rocketpy/motors/HybridMotor.py
rocketpy/motors/LiquidMotor.py
rocketpy/motors/Motor.py
rocketpy/motors/SolidMotor.py
rocketpy/motors/TankGeometry.py

The documentation regarding Tanks and Motor additions were outdated and did not reflect the implemented code. Generic motors were also lacking proper constructor description.
The documentation was updated.

DOC: update motor docstrings regarding coordinate systems

---

rocketpy/Flight.py
rocketpy/Function.py

The forces at the rail buttons can be sctricly negative, therefore the arguments that compute the max forces in the rail buttons will return exactly the opposite of what we usually want: the least intense load.
The Function class now can calculate the maximum (and min) absolute value of a function.
- I will implement tests in another PR.
- If you think that we should improve documentation (of Flight or Function), please feel free to suggest it.

BUG: absolute value of the rail button forces

---

rocketpy/AeroSurface.py
rocketpy/plots/aero_surface_plots.py

Warnings are raised when they should not be and the `draw()` method is not in the `aero_surfaces_plot.py` file
The warnings have been fixed by adding a special check to see if the nosecone is of `elliptical` shape, and the method has been moved to the correct place.
I've also improved the documentation a bit.
Special thanks to @CabGT for doing all the hard work here.

ENH: Minor Improvements and Replacement of NoseCone.draw()

---

rocketpy/utilities.py

The apogee by mass function prints "Rocket Dry Mass (kg)" when it is stilll modifying the Rocket Mass (without the motor). 
I think this is not exactly a bug, but the current behavior is giving false ideas to the final user.
2 code lines solving the problem
Bug reported via private message today

MNT: clearly specify the rocket mass in utilities

---

rocketpy/mathutils/function.py
rocketpy/motors/solid_motor.py
tests/acceptance/test_ndrt_2020_rocket.py
tests/test_flight.py

The conventional `pytest` run raised some warnings regarding wrong `burn_time` input and integration precision not being achieved.
Furthermore, the way the `SolidMotor` grain regression ODE was written could be improved a bit both in speed and readability with better local variable naming/choice.
The `pytest` warnings were solved and, locally, they do not show up anymore. In order to improve the `SolidMotor` grain regression ODE, the local variable scheme was changed and the simulation jacobian was added following `scipy.solve_ivp` recomendation for the `LSODA` solver.

FIX: Motors UnitTesting Warnings

---

rocketpy/mathutils/function.py

When adding a constant value to a discrete Function, the extrapolation method is not maintained. This PR fixes this issue

BUG: Maintaing Extrapolation when Adding Discrete Functions with Constants

---

rocketpy/motors/liquid_motor.py
rocketpy/motors/tank.py
rocketpy/plots/liquid_motor_plots.py
rocketpy/plots/tank_plots.py

ENH: liquid motors draw

---

rocketpy/motors/solid_motor.py
rocketpy/plots/rocket_plots.py
rocketpy/plots/solid_motor_plots.py

ENH: solid motors draw

---

rocketpy/tools.py

There is this function `tools.find_closest()` that have been used inside the Flight class. I faced it when working in the last BUG fix #438 . It can be better tested and explained with some examples in its docstring.
The docstring of the function was modified. 
This PR is complementary to the last one, just wanted to put it in here to alleviate last PR. 
None

MNT: adding example docs to the find_closest() function

---

rocketpy/simulation/flight.py
tests/test_flight.py

- I'm getting an error when initializing a flight object using a motor that has an burn_out_time lower than the initial time step.
- The error happens when trying to access the max acceleration during the burn time 
- This is particularly common for deployable or multi-stage flight simulations.
- ValueError: attempt to get argmax of an empty sequence
A simple code line solved the problem, and I added a simple test to avoid getting this problem again.

BUG: flight.prints.max_values() fails when launching an EmptyMotor

---

rocketpy/plots/environment_plots.py

the wind_u and wind_v labels are not being used for plotting the wind profile in the Environemnt.all_info() method. This makes it impossible to be read.
Simply adding the legend where it is needed.
Simple fix based on a recent feedback we got at EuRoC this year.

MNT: fix env plots legends

---

rocketpy/simulation/flight.py
tests/test_flight.py

If by any chance you want to know the state vector that corresponds to a specific time of the flight, there's no easy way to do so.
There's this new method that returns the numpy array of the solution state at a specific time. If the user choose a time that do not exists in the timesteps, a warning is raised and the code automatically changes to the closest time step.
- This feature is particularly important for us to work on multi-stage and deployable flights.
- I was not sure if it was better to return the np.array object or a list. I chose array because I thought it could be more useful and faster, but honestly this was arbitrary and I don't think there is a big difference between the two options.
- as I am creating this PR on windows, I wonder if the integrators of the Flight class …

ENH: new Flight.get_solution_at_time() method

---

rocketpy/plots/rocket_plots.py

Since the introduction of `Rocket.draw` and the change of `Rocket.cp_position` as a Mach dependent function were done in parallel (both merged with only one day difference, without proper rebasing or merging the develop branch before approval), a specific part of the code introduced in #419 was not up to date with the changes made in #377. 
This made it so a bug was created where `Rocket.draw` failed.
The bug was fixed.

FIX: cp_position call in rocket.draw to work with mach dependent cp_position

---

rocketpy/motors/motor.py

There was a small issue when using the `GenericMotor` class and trying to plot its mass_flow_rate.
Now we can finally have a mass_flow_rate in the GenericMotor class
The idea of separating mass_flow_rate from total_mass_flow_rate is still weird to me

ENH: Add mass_flow_rate() to GenericMotor class

---

rocketpy/plots/hybrid_motor_plots.py
rocketpy/plots/liquid_motor_plots.py
rocketpy/plots/motor_plots.py
rocketpy/plots/solid_motor_plots.py

A lot of repeated code in the motors' plots classes
`_SolidMotorPlots`, `_HybridMotorPlots` and `_LiquidMotorPlots` now inherit `_MotorPlots`
There are a lot of repeated code in `_SolidMotorPlots` and `_HybridMotorPlots` I could not find a good solution for it. I tried using multiple inheritance in `_HybridMotorPlots` but it went south really fast
Also, this is really useful for Motor Draws #436

ENH: Add _MotorPlots Inheritance to Motor Plots Classes

---

.github/workflows/test_pytest.yaml
README.md

We run tests everytime but we don't see the code coverage percentage
Adding codecoverage integration according to this: https://app.codecov.io/gh/RocketPy-Team/RocketPy/new.
This still needs to be tested before merging.
None

MNT: add codecov integration

---

docs/requirements.txt
docs/user/first_simulation.rst

The documentation lacked proper description on simulation data export.
A new section in the `getting started` page was added to cover the basics of using the `Flight.export_data`.

DOC: add documentation for flight data export.

---

docs/user/first_simulation.rst
docs/user/motors/hybridmotor.rst
docs/user/motors/liquidmotor.rst
docs/user/motors/tanks.rst
docs/user/rocket.rst

With the new draw methods added, some parts of the documentation could be improved. This PR does that

DOC: Include Draw Method in Docs

---

rocketpy/mathutils/function.py

Scipy's  `optimize.root` gives an array of length 1 to the Function object inside `find_input`. Currently if a Function receives an Iterable, it returns a list. This was not always the case before #451.
Now `find_input` should always work, independent of the Function source

BUG: Fix find_input() Function to Return a Single Value

---

.pylintrc
rocketpy/mathutils/function.py
rocketpy/motors/liquid_motor.py
rocketpy/plots/rocket_plots.py

You run the tests, they all pass, but there are still some warnings behind.
Using the `pytest -v -W error` flag I was able to identify some warnings in the execution and give them the proper treatment. 
Please read the commits descriptions for more details.
In the future we may want to update the SEBML curve to avoid getting in the new warning

MNT: solve warnings

---

.github/pull_request_template.md
CHANGELOG.md

We often forget about what is being included in our releases.
There's this CHANGELOG.md special file in the RocketPy root folder. This follows some internet standard format https://keepachangelog.com/en/1.1.0/
The idea is to update the changelog file every time we submit a PR that rings either a code addition, code change or code fix. 
We must be short in the descriptions.
Accepting suggestions before merging.
Thanks for bringing this out @giovaniceotto .

DOC: Add RocketPy change log file

---

docs/conf.py
docs/user/installation.rst
rocketpy/rocket/rocket.py
setup.py
tests/test_rocket.py

When using the `nose_to_tail` coordinate system for the `Rocket` class, the sign of the static margin was inverted since a sign correction was applied twice, as noticed by @MateusStano.
Things just work now. One of the sign corrections was removed. Ironically, we had tests for this, but they were not working properly. This has also been fixed.
Version has been bumped up to v1.1.1 so that a hotfix can be released.
This bug was reported by Bob Brown [D&W] (MΦNK3Y#2638) through our Discord server.

HOTFIX: Negative Static Margin

---

CHANGELOG.md
rocketpy/mathutils/function.py
tests/test_function.py

Operations that involve reverse `Function` operations with `numpy.ndarrays` result, usually unexpectedly, in a `numpy.ndarray` as a result. This happens since `numpy.ndarray` implement an `__radd__` that overrides `Function.__radd__` operation. 
The variable `__array_ufunc__` is a way to enforce `Function` priority regarding reverse operations.
This same issue was found during `mathutils.vector` and `mathutils.matrix` development and the same fix was applied (using `__array_ufunc__`).

ENH: Function Reverse Arithmetic Priority

---

CHANGELOG.md
docs/conf.py
docs/user/installation.rst
rocketpy/mathutils/function.py
setup.py
tests/test_function.py

As reported by @styris00, the following code shows an error with `Function.get_value_opt` when used with 2D functions.
```
import numpy as np
from rocketpy import Function
arr = np.array([(1, 1, 2), (3, 6, 8),
(8, 8, 9)])
myFun = Function(
arr,
interpolation="shepard",
extrapolation="natural",
title="myFun"
)
myFun.set_get_value_opt()
print(myFun.get_value(1, 1)
print(myFun.get_value_opt(1, 1))
```
Output is:
```
2.0
1.0
```
The bug was fixed.

FIX: Broken Function.get_value_opt for N-Dimensional Functions

---

CHANGELOG.md
rocketpy/rocket/parachute.py
rocketpy/rocket/rocket.py

- The parachute trigger option "apogee" is case sensitive, so the triggerfunc is not set if you use "Apogee" or "APOGEE" instead of the expoected "apogee" value.
- Worse is that the Parachute class doesn't raise any error is the user pass a string like "Apogee" or "AnyOtherThing", so the user just gets an error message when simulating the Flight class
- Refactor the Parachute class init just a bit. 
- Using the built-in lower() method to compare the string without being case-sensitive.
- You're gonna know if the triggerfunc cannot be set after initializing the Parachute class.
Reported by jackson.dendy on discord tonight, from the univ of Tenesse.

ENH: Parachute trigger doesn't work if "Apogee" is used instead of "apogee"

---

CHANGELOG.md
rocketpy/rocket/parachute.py

This is useful for debugging or when you simply call `Rocket.parachutes` and want to see something more readable.
Opening this now, can describe the PR later, sorry.

MNT: Add __repr__ method to Parachute class

---

tests/conftest.py
tests/test_function.py
tests/test_solidmotor.py

1. Currently, test_solidmotor.py creates a motor inside the testing module called 'test_reshape_thrust_curve_asserts_resultant_thrust_curve_correct', which is not adequate. This method also does not contains comments.
2. Inside the test_function.py testing module the 'test_differentiate' method relies on manually passing the inputs. 
1. The solution employed was to create a motor in conftest.py, which was called 'cesaroni_m1670_shifted', and which was used in the test method called 'test_reshape_thrust_curve_asserts_resultant_thrust_curve_correct'. Comments were also made.
2. It was properly refactored and new comments were made. Also, @pytest.mark.parametrize was introduced to make the test method ready to handle more test cases. This test was introduced in …

TST: solid_motor.py testing refactors

---

CHANGELOG.md
docs/user/function.rst
docs/user/motors/thrust.rst
docs/user/rocket.rst
rocketpy/motors/hybrid_motor.py
rocketpy/motors/liquid_motor.py
rocketpy/motors/motor.py
rocketpy/motors/solid_motor.py
rocketpy/rocket/aero_surface.py
rocketpy/rocket/rocket.py

Docs related to reading files mentioned that the files must contain no headers
Now those docs mention that the files can contain headers

DOC: Update Header Related Docs

---

CHANGELOG.md
rocketpy/motors/hybrid_motor.py
rocketpy/motors/motor.py
rocketpy/motors/solid_motor.py

`GenericMotor.exhaust_velocity` is being decorated by `funcify_method`, which makes it (a float essentially) into a `lambda` defined `Function`. This causes everything that depends on it algebraically to become `lambda` defined `Functions` as well.
More specifically, this contaminates `GenericMotor.mass_flow_rate`, which in turn contaminates `GenericMotor.propellant_mass` (which actually includes an `integral_function` of the `lambda` `GenericMotor.exhaust_velocity` 🫣). Well, in the end, this contaminates `Rocket.total_mass`, which is used extensively by the `Flight` class during a simulation.
In summary, this use of `funcify_method` causes the `Flight` class to take forever (literally) to run.
What can I say? Changing the decorator from `funcify_method` to `cached_property` makes the sun …

FIX: changes Generic Motor exhaust velocity to cached property

---

tests/conftest.py

linearly_interpolated_func
I found this bug on a pytest fixture.
The `linearly_interpolated_func` fixture is now using the linear interpolation method
Updated the docstring as well.
the tests are passing even if adter the change

MNT: Update interpolation method in linearly_interpolated_func

---

CHANGELOG.md
docs/conf.py
docs/notebooks/deployable_payload_example.ipynb
docs/notebooks/dispersion_analysis/dispersion_analysis.ipynb
docs/notebooks/dispersion_analysis/parachute_drop_from_helicopter.ipynb
docs/notebooks/getting_started_colab.ipynb
docs/user/installation.rst
rocketpy/motors/hybrid_motor.py
rocketpy/motors/motor.py
rocketpy/motors/solid_motor.py
setup.py

- DOC: Change from % to ! in the first cell to run properly in Colab. [#496](https://github.com/RocketPy-Team/RocketPy/pull/496)
- FIX: changes Generic Motor exhaust velocity to cached property [#497](https://github.com/RocketPy-Team/RocketPy/pull/497)

REL: v1.1.4

---

rocketpy/mathutils/function.py
tests/unit/test_function.py

Calls to get_value_opt for shepard interpolation were slower.
Calls to get_value_opt for shepard interpolation are quicker (using Numpy vectorized operations).

ENH: optimization of get_value_opt in set_get_value_opt of class Function

---

rocketpy/mathutils/function.py
tests/test_function.py

There were no functions to smooth a Function object.
We added a "low_pass_filter" method applying an exponential smoothing to a Function object. This function takes a parameter "alpha" you have to chose to smooth the function.
For a given dataset, the larger alpha is, the more closely the filtered function returned will match the function
the smaller alpha is, the smoother the filtered function returned will be (but with a phase shift)

ENH: add Function.low_pass_filter method

---

CHANGELOG.md
rocketpy/plots/rocket_plots.py

Try to call the Rocket.draw() method without adding a motor to the rocket. The EmptyMotor will be used as default, the plot will be created but an error will also be displayed 
Changed the order of some operations and solved the problem.
Bug reported from UPV-Faraday rocketry team (Valencia, Spain).

BUG: EmptyMotor is breaking  the Rocket.draw() method

---

rocketpy/mathutils/function.py

The code is able to filter data (of a CSV file) but doesn't save the filtered dataset.
Once you filter a dataset, this one is saved in a CSV file.

ENH : Add of a line for saving the filtered dataset

---

CHANGELOG.md
rocketpy/plots/flight_plots.py

It's getting into my nerves since 2021 or even more!
- This is the magic line: `ax1.set_box_aspect(None, zoom=0.95)`
- And this is the wizard that has shown me how to perform such skill: https://stackoverflow.com/a/77580433

BUG: 3D trajectory plot not labeling axes

---

CHANGELOG.md
rocketpy/mathutils/function.py
tests/test_function.py

The PR #451 introduced a standard for the `get_value` arguments regarding multidimensional Functions that were not updated everywhere in code: the method `set_discrete` for 2D Functions breaks. One may verify it by running on `master`:
```bash
>>> from rocketpy import Function
>>> f = Function(lambda x,y: x**2 + y**2)
>>> f.set_discrete(-10,10,25)
```
During debug there were two root causes for the error that were fixed:
1. `get_value` call still used one argument for two dimensional domains: a simple argument separation was enough for a fix.
2. `__check_user_inputs` method did not account for the possibility of a `Function` being a source.
Basic tests were implemented. Since this is a hotfix, I avoided changing much, but a full fix involves exploring issue #481 and improving the sets for …

BUG: Invalid Arguments on Two Dimensional Discretize (HOTFIX).

---

.pylintrc
CHANGELOG.md
rocketpy/plots/flight_plots.py
rocketpy/simulation/flight.py
tests/test_flight.py

The method `export_pressure` incorrectly calls the `lists`: `parachute.clean_pressure_signal` and `noisy_pressure_signal` as if they were functions. Furthermore, this data is not set before the call of the `all_info`, which could lead to invalid exports if it was working.
The issue when trying to export the pressure was: 
```py
3091 for parachute in self.rocket.parachutes:
3092     for t in time_points:
-> 3093         p_cl = parachute.clean_pressure_signal(t)
3094         p_ns = parachute.noisy_pressure_signal(t)
3095         file.write(f"{t:f}, {p_cl:.5f}, {p_ns:.5f}\n")
TypeError: 'list' object is not callable
```
The employed fix was to call the method that set these values not in the `all_info`, but after `Flight` computations. On top of that, the incorrect `list` calls were …

BUG: Parachute Pressures not being Set before All Info.

---

CHANGELOG.md
docs/conf.py
docs/user/installation.rst
setup.py

We have 2 merged PRs at master without a release
Updates rocketpy to v1.1.5 and updates the changelog.
We need to create a release and publish to PyPI.

REL: Update RocketPy version to 1.1.5

---

CHANGELOG.md
docs/user/function.rst
rocketpy/mathutils/function.py

While using the new low_pass_filter method, I noticed some minor adjustments could be done, let's see:
- Persist the inputs, outputs and title of the original Function
- Improve the method docstring
- Add an example to the .rst file

ENH: improve Function.low_pass_filter and adds docs

---

.pylintrc
CHANGELOG.md
rocketpy/simulation/flight.py
rocketpy/tools.py

We take quaternions (euler parameters) and calculate euler angles inside the flight class, but this code cannot be reused in other applications.
- The quaternions -> angles conversions were moved to the tools.py module, thus allowing for other classes to access these functions.
- The Flight class was adjusted to use the new functions.
This is going to be quite useful for the `rocketpy.simulation.FlightDataImporter` class.

MNT: Encapsulate quaternion conversions

---

.pylintrc
CHANGELOG.md
rocketpy/environment/environment.py
rocketpy/simulation/flight.py
tests/test_environment.py

The `find_input` calls to get the height AGL from the pressure value for the parachute trigger was slowing down the simulation drastically:
Now a `Function` is created in `Environment` called `barometric_height` and that is called inside the `Flight` class instead:
This `find_input` call was added in #345

ENH Precalculate Barometric Height

---

docs/notebooks/dispersion_analysis/dispersion_analysis.ipynb

The dispersion analysis notebook uses, on its last cell, the library imageio, but does not install it at any point, nor is it a dependency. Executing the whole notebook without having the library prompts a "ModuleNotFoundError" at the last cell.
Install imageio at the 'Install and Load Libraries' section.
The installation is done exclusively for this notebook, so there are no changes to dependencies.

DOC: Installing imageio library on dispersion analysis notebook

---

docs/notebooks/deployable_payload_example.ipynb
docs/notebooks/dispersion_analysis/dispersion_analysis.ipynb
docs/notebooks/dispersion_analysis/parachute_drop_from_helicopter.ipynb
docs/notebooks/getting_started_colab.ipynb
rocketpy/environment/environment_analysis.py
rocketpy/mathutils/function.py
rocketpy/plots/flight_plots.py
rocketpy/rocket/aero_surface.py
rocketpy/simulation/flight.py
rocketpy/simulation/flight_data_importer.py
tests/test_flight_data_importer.py
tests/test_genericmotor.py
tests/test_tank.py
tests/unit/test_rocket.py
tests/unit/test_solidmotor.py

As described in issue #526, the repository is cloned on four notebooks to obtain the data files required for computations. However, the total size of the data files is, in general, very small (less than 1 MB), and we are cloning more than 1 GB, hence getting a lot of unnecessary information.
Instead of using the !git clone, we use the [curl](https://curl.se/docs/tutorial.html) command to download only the required data files from raw GitHub user content from RocketPy's repository. The path name for data files also changed accordingly, e.g. "../../data/calisto/powerOffDragCurve.csv" was changed to "powerOffDragCurve.csv" .
Markdown comments were changed to match the commands. Instead of stating we are going to clone the repository, we state that we are downloading the data files.
The …

DOC: Replacing git clone command with curl in notebooks.

---

CHANGELOG.md
rocketpy/environment/environment_analysis.py
rocketpy/mathutils/function.py
rocketpy/plots/flight_plots.py
rocketpy/rocket/aero_surface.py
rocketpy/simulation/flight.py
rocketpy/simulation/flight_data_importer.py
tests/test_flight_data_importer.py
tests/test_function.py
tests/test_genericmotor.py
tests/test_tank.py
tests/unit/test_rocket.py
tests/unit/test_solidmotor.py

The Function class did not get the inputs and outputs name from the header of CSV file.
If the CSV file has headers, the input and output parameters that are left `None` will be set from the header information.

ENH: Function inputs from CSV file header.

---

.github/pull_request_template.md
.gitignore
Makefile
requirements-tests.txt

The current Makefile is dated from more than 2 years ago, and I'm under the impression that almost none of our developers (including me) use it so often.
I updated (and hopefully improved) the Makefile, now adding new commands to help us during development phase.
You can now use the following commands:
- `make pytest`
- `make slow`
- `make coverage`
- `make coverage-report`
- `make install`
- `make isort`
- `make black`
- `make pylint`
- `make build-docs`
- There's a strange error happening when running `make pylint`, but it is being ignored by the `-` sign and should not affect the performance, so don't worry about that.
- Please ensure the commands are running properly in your local machines! I'm curious to see the behaviour when running in Windows, @MateusStano .

MNT: update Makefile

---

CHANGELOG.md
docs/development/style_guide.rst
rocketpy/mathutils/function.py

Some comments made in the #536 PR conversation.
Read the commit messages one by one.

MNT: Final refactor before v1.2

---

CHANGELOG.md
rocketpy/prints/rocket_prints.py
rocketpy/rocket/aero_surface.py
rocketpy/rocket/rocket.py
tests/test_rocket.py

See #557.
Issue #557 is fixed.

BUG: Add reference area factor correction to aero surfaces (solves #557)

---

CHANGELOG.md
rocketpy/motors/motor.py

As described in #473, 'export_eng' method does not work for liquid motors since it does not have grain related attributes.
The Motor method 'export_eng' now works for liquid motors and the .eng file is created. For liquid motors, the first two parameters written to the file are now zeros, since those are grain related attributes.
Below is the '.eng' file generated for the liquid motor defined in the SEB_liquid_motor.ipynb notebook.

BUG: Motor method 'export_eng' for liquid motors bug fix. (solves #473)

---

CHANGELOG.md
rocketpy/mathutils/function.py

Every time you call the the `Function.compare_plots` method, it will display the plot regardless of your intentions.
Added a new argument to the method.
Plus updated the docstring, which was a bit old.
Quite easy to review this one.

ENH: Optional argument to show the plot in Function.compare_plots

---

CHANGELOG.md
rocketpy/mathutils/function.py
tests/unit/test_function.py

Different datasets present undesired values that we usually have to remove manually.
The Function class now can remove outliers from the source (if array like) using the IQR method.
- This was saved in my machine for a while. It is simple but has been working without problems.
- It will not be included in the version v1.2.0, but in the 1.3.0 instead.

ENH: adds `Function.remove_outliers` method

---

CHANGELOG.md
rocketpy/rocket/rocket.py
rocketpy/simulation/flight.py
tests/acceptance/test_bella_lui_rocket.py
tests/test_flight.py
tests/unit/test_utilities.py

When calculating the parachute forces in the `Flight.u_dot_parachute` method, the code is using the rocket's mass without the motor's dry mass. It should be using the `Rocket.dry_mass` value instead.
Fixed the bug, updated docs and tests.
- Quick obs.: Acceptance tests should prevent bugs like this, @lucasfourier @GabrielBarberini !!
- This bug was captured today by the Faraday team, Spain. Many thanks to their contribution!

BUG: wrong rocket mass in parachute u dot method

---

rocketpy/environment/environment.py
tests/fixtures/environment/environment_fixtures.py
tests/fixtures/flight/flight_fixtures.py
tests/test_environment.py
tests/test_flight.py
tests/test_plots.py
tests/unit/test_environment.py

- Small refactoring with emphasis on test clarity and DRY;
- FUP on [RFC - RocketPy pytest architecture](https://docs.google.com/document/d/14GBEDzqXjn7YAg4s0ePvL0SW0PoGbqB4UxN0IZ5J-nQ/edit#heading=h.jvat5sscp9g9)

TST: Environment unit tests refactoring

---

CHANGELOG.md
rocketpy/prints/flight_prints.py

The code used within the `_FlightPrints` class is becoming quite outdated.
It is basically the same code since rocketpy was created.
There are some quick improvements that we can do, while not changing the behavior of the class.
The class still gives the same results, but with some refactoring like:
- F-strings as faster in python, let's use them!
- Added a docstring to the module, this may helps both users and devs. Now the `help(rocketpy.prints.flight_prints)` command will work.
- useless comments were removed (don't state the obvious with comments, that's annoying and does help anyone)
- docstrings were updated
- no code line is longer than 88 columns (pylint and flake8 restriction)
- improve parachute printing
- Reviewers, please let me know if you have any suggestion regarding these …

MNT: Refactor flight prints module

---

CHANGELOG.md
rocketpy/mathutils/function.py
tests/test_flight.py
tests/test_function.py
tests/unit/test_function.py

1. The input parameters of the Funciton class are all checked in a very disorganized way. This would lead to redundant checks and overall slowing down of the class
2. all interpolations used in `get_value_opt` were using `np.searchsorted`, which was slow
1. Validation has been reworked as to follow the order: `source` -> `interpolation` and `extrapolation` -> `inputs`, `outputs` and `title`. The `get_value_opt` function is now modularized  and is defined according to the current `interpolation` and `extrapolation`
2. `bisect_left` is now used instead of `np.searchsorted`. This cuts the execution time by half in a `u_dot_generalized` call.
The `Function` class should behave exactly the same as before.
- There is an attribute called `__img_dim__` that was never used and was always equal to …

ENH: Function Validation Rework & Swap `np.searchsorted` to `bisect_left` 

---

CHANGELOG.md
rocketpy/rocket/rocket.py
rocketpy/simulation/flight.py
tests/test_flight.py

If a simulation is using the new EOMs and has a time node at the motor burn-out time, an outlier acceleration value might be calculated:
This is due to the second-order differentiation of `rocket.total_mass` blowing up due to numerical errors. Swapping this to `motor.total_mass_flow_rate` gives the following:
This makes `u_dot_generalized` more similar to the old udot

BUG: Swap `rocket.total_mass.differentiate` for `motor.total_mass_flow rate`

---

CHANGELOG.md
rocketpy/environment/environment_analysis.py
rocketpy/mathutils/function.py
rocketpy/mathutils/vector_matrix.py
rocketpy/motors/hybrid_motor.py
rocketpy/motors/liquid_motor.py
rocketpy/motors/motor.py
rocketpy/motors/solid_motor.py
rocketpy/motors/tank_geometry.py
rocketpy/plots/flight_plots.py
rocketpy/rocket/aero_surface.py
rocketpy/tools.py

This PR completes the previous PR #541, which solves the issue #531 
Use the `cached_property` class from functools instead of rocketpy.tools.
I used git cherry-pick to save Daniel's commit.

DEP: delete deprecated rocketpy.tools.cached_property

---

CHANGELOG.md
rocketpy/environment/environment.py
rocketpy/tools.py
tests/fixtures/environment/environment_fixtures.py
tests/test_environment.py
tests/unit/test_environment.py

It is annoying that several tests fail due to bad approach of fetching external APIs data.
Fixed the issue #449 . Code is running ok, I also testes slow tests.
I was really tired of seeing the Wyoming atmosphere model failing in our tests.

ENH: Exponential backoff decorator (fix #449)

---

CHANGELOG.md
rocketpy/plots/rocket_plots.py

The method of `_RocketPlots` relating to the rocket drawing was too big and hard to change/improve/maintain
The `.draw()` method has been separated into several different methods. No code relating to the plot has been changed.
I was trying to add sensors to the drawing and it was really hard to work with the drawing, so I refactored it.
A quick note:
- There are a few lines of repeated code that could still be turned into functions. These are usually some matplotlib one-liners. I did not create a function for these because it affected readability negatively.

MNT: Modularize Rocket Draw

---

.github/workflows/test_pytest.yaml

I am removing macOS + python 3.8 from the tests matrix. 
This will avoid a hdf5 error that is preventing us to install rocketpy on macOS using python 3.8
For future reference: https://github.com/h5py/h5py/issues/2408

TST: temporary changing git actions

---

CHANGELOG.md
pyproject.toml

The installation of optional dependencies `env-analysis` and `àll` is not working as expected, yielding the following results:
<details>
<summary>env-analysis install results</summary>
<br>
<br>
<p>The same happens with `env_analysis`.</p>
</details>
<details>
<summary>"all" install result</summary>
<br>
</details>
Changing the naming of `env_anaysis` to the [python package normalized](https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization) `env-analysis` fixes the first installation issue.
The second was the addition of the `all` to the optional dependencies.
The recursive syntax to generate the `all` in the `pyproject.toml` file is only supported from [`pip>=21.2`](https://pip.pypa.io/en/stable/news/#v21-2) (from 2021). The `+` symbol from …

FIX: Optional Dependencies Naming in pyproject.toml.

---

CHANGELOG.md
docs/user/function.rst
rocketpy/mathutils/function.py
tests/unit/test_function.py

The `Function.differentiate()` method is the only method that can be used to derivate Function objects.
The new, powerful, and fast `Function.differentiate_complex_step()` method is here!
This method will be used to speed up simulations in future PRs.
This PR will close the #131 issue, a really old feature request of our repository.

ENH: Complex step differentiation

---

CHANGELOG.md
rocketpy/plots/rocket_plots.py

When you use a callable object as the source of your power_on or power_off curves in the Rocket class, the `all_info()` method will break because `self.rocket.power_on_drag.x_array` is inexistent
Solved the issue by  adding a try/except block that will prevent code from breaking in the situation 
None

BUG: plot drag curves when function source is callable

---

CHANGELOG.md
rocketpy/rocket/aero_surface.py

Bug fix issue #610 .
The `find_radius` method inside the `NoseCone` class computes the square of its argument `x`. The lambda function, however, passes a list to it, causing a `TypeError`.
Just pass the value instead of the list.

BUG: Fixes nose cone bluffness issue #610

---

CHANGELOG.md
pyproject.toml

One of the classifiers of the new `pyproject.toml` file is not recognized.
Comparing the current classifiers with `v1.2.2` it seems there is an added one.

MNT: Alter PYPI classifier naming.

---

CHANGELOG.md
docs/conf.py
docs/user/installation.rst
pyproject.toml

There is an issue with package discovery in current build with `pyproject.toml`. 
This PR allows for the discovery of `rocketpy` main package and its submodules.

BUG: pyproject.toml Main Module Finding.

---

.github/workflows/test_pytest.yaml

CI is breaking due to a problem with netcdf4 installation on windows with python 3.8.
This was caused due to the latest release of netcdf4, version 1.7.0
GitHub Actions will no longer run on windows with python 3.8, but the python 3.12 is kept for os compatibility check.
This is a temporary fix that will be rolled back after netcdf4 fix of: https://github.com/Unidata/netcdf4-python/issues/1329
No further comments.

DEV: remove windows py3.8 from ci

---

.github/workflows/lint_black.yaml
.github/workflows/publish-to-pypi.yml
.github/workflows/test_pytest.yaml
.pylintrc
CHANGELOG.md
docker-compose.yml
docs/development/docker.rst
docs/user/installation.rst
pyproject.toml

As Python 3.8 nears the end of its life in a few months and many of rocketpy dependencies having removed it from official support, it is time to drop rocketpy Python 3.8 support.
This PR raises the minimum Python requirements to 3.9.
Short PR, but I advise to review it carefully. It is easy to mess up by accident the version numbers, or not catch a place that should be changed.

MNT: Bump Minimum Python version to 3.9.

---

.github/workflows/test-pytest-slow.yaml

Sometimes we "forget" about the slow tests for weeks and we get outdated tests.
Every 2 weeks, the slow tests will be executed on GitHub Actions

DEV: adds scheduled test with pytest slow option

---

CHANGELOG.md
rocketpy/simulation/flight.py
tests/integration/test_environment.py
tests/integration/test_flight.py
tests/unit/test_monte_carlo.py

Recently reported on discord:
The problem was related to Function interpolations. I added the apogee state to the state solution so it created a point at the minimum value of the free stream speed curve (i.e. the apogee). This way we reduced the error when evaluating the stream speed at apogee.

ENH: Insert apogee state into solution list during flight simulation

---

CHANGELOG.md
rocketpy/rocket/aero_surface/rail_buttons.py
rocketpy/rocket/rocket.py
rocketpy/simulation/flight.py
tests/unit/test_rocket.py

A small change (addition of the rocket_radius attribute) was made to the RailButtons class to resolve issue #606. For the change to work in practical simulations, small changes were made to the rocket.py (add_surfaces method) and flight.py (u_dot_generalized method) files.
It is now possible to use the RailButtons class in the way the user tried, without major changes to the code and with everything apparently working.

ENH: adding rocket radius to RailButtons class

---

CHANGELOG.md
rocketpy/simulation/flight.py

Found by team RED on Discord.
Controller time nodes were being ignored and discarded  in the merging of the time nodes, now they are correctly considered

BUG: Time Node Merge Not Including Controllers

---

.github/workflows/test_pytest.yaml
rocketpy/mathutils/function.py

for some weird reason the CI is installing numpy 1.26 instead of 2.0 since last week.

DEV: fix tests with numpy2

---

CHANGELOG.md
rocketpy/plots/flight_plots.py

- I noticed it was just a matplotlib plotting matter, not a problem with the calculations.

BUG: fix the Frequency Response plot of Flight class

---

CHANGELOG.md
rocketpy/environment/environment.py

Extrapolation was being incorrectly set on `pressure_ISA` which was causing it to raise an undesired warning

BUG: Pressure ISA Extrapolation as "linear"

---

CHANGELOG.md
docs/user/motors/genericmotor.rst
docs/user/motors/motors.rst
rocketpy/motors/hybrid_motor.py
rocketpy/motors/liquid_motor.py
rocketpy/motors/motor.py
rocketpy/motors/solid_motor.py
tests/unit/test_genericmotor.py

the static method to create motors from eng files did not exist.
method created and working

ENH: Adds GenericMotor.load_from_eng_file() method

---

CHANGELOG.md
rocketpy/motors/liquid_motor.py
rocketpy/motors/motor.py

Adding a `Tank` with zero mass flow rate **at all times** causes an error on ``exhaust_velocity`` computation.
Zeros were added as defaults to the `exhaust_velocity` calculation and the `total_mass_flow_rate` formula as changed to an identical one that avoids possible zero divisions errors.

BUG: Zero Mass Flow Tank causing Empty Velocity Data

---

CHANGELOG.md
rocketpy/rocket/aero_surface/nose_cone.py
rocketpy/rocket/aero_surface/tail.py
tests/unit/test_flight.py

Prandtl-Glauert corrections applied to Tail and Nose produced some unexpected behaviors.
This PR rollback the Tail and Nose aerodynamic to the earlier state.

BUG: Rollback Prandtl-Glauert corrections for Tail and Nose.

---

tests/conftest.py
tests/fixtures/generic_surfaces/generic_surfaces_fixtures.py
tests/fixtures/generic_surfaces/linear_generic_surfaces_fixtures.py
tests/unit/test_generic_surfaces.py
tests/unit/test_linear_generic_surfaces.py

No tests.
Unit tests for generic surfaces

TST: generic surfaces

---

rocketpy/mathutils/function.py

Currently, lambda defined `Function` are not correctly saved when using `savetxt`. The problem was that a np.array was being passed for the evaluation of the lambda.
The solution was to use `Function`'s  `get_value_opt` to call on the lambdas.

BUG: `savetxt` Not Accepting lambda Functions

---

rocketpy/mathutils/function.py

Functions of a single point (`Function([[1,2]]`) do not currently work because of an added validation for source shape.
I have corrected the validation to account for one point Functions

BUG: Single Point Functions Can Not Be Defined

---

CHANGELOG.md
rocketpy/mathutils/vector_matrix.py

The `Vector` class now being used for `Component` position does not have proper encoding. This breaks MonteCarlo inputs export.
This PR is a hotfix that implements the necessary changes to encode the `Vectors`. Full encoding support should be bought by #695 .

BUG: Vector encoding breaks MonteCarlo export.

---

CHANGELOG.md
README.md
docs/user/environment/1-atm-models/soundings.rst
rocketpy/environment/environment.py
rocketpy/environment/fetchers.py
rocketpy/mathutils/function.py
tests/integration/test_environment.py

Unfortunately, there's no workaround to get these data again, since the governamental agency (NOAA) decided to no longer expose the model to the public.

DEP: deprecate NOAA's RuC sounding

---

CHANGELOG.md
rocketpy/control/controller.py
rocketpy/rocket/rocket.py

Some arguments passed to `__init__` of the `_Controller` class were not being saved. This PR fixes this issue
This is important for controller/airbrakes serialization.
Should be merged after #701

BUG: Initialize `_Controller` Init Parameters 

---

CHANGELOG.md
rocketpy/motors/motor.py

fixed zero mass check for motor dry_mass. Local tests are passing.

BUG: Fix Motor Zero Dry Mass Check

---

docs/reference/classes/sensors/index.rst
docs/user/environment/0-setup/elevation.rst
docs/user/environment/1-atm-models/soundings.rst

Fixing documentation build and ``Environment`` related examples.
There are documentation warnings and other fixes that could easily be done to improve docs format and appearance given the addition of new features. However, the purpose of this PR is simply to successfully build the documentation.

DOC: Fix docs References and Examples Build.

---

CHANGELOG.md
rocketpy/motors/hybrid_motor.py
rocketpy/motors/liquid_motor.py
rocketpy/motors/motor.py
rocketpy/motors/solid_motor.py
rocketpy/prints/hybrid_motor_prints.py
rocketpy/prints/liquid_motor_prints.py
rocketpy/prints/motor_prints.py
rocketpy/prints/rocket_prints.py
rocketpy/prints/solid_motor_prints.py
rocketpy/rocket/rocket.py

Solves issue #671 .
From what I understood from the issue, the information required to be printed was the the ratio of the dry mass by the total mass. I saw some [sources](https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/mass-ratios/) computing the propellant mass ratio, which I believe is the opposite (inverse of the specified ratio).

ENH: add structural to total mass ratio for motor and rocket

---

.github/workflows/test-pytest-slow.yaml
.github/workflows/test_pytest.yaml
rocketpy/tools.py

with also a few other additions

DEV: updates workflows to include python 3.13

---

CHANGELOG.md
docs/conf.py
docs/user/installation.rst
pyproject.toml

Obs.: my vscode is automatically deleting blank spaces at end of lines.

REL: rocketpy v1.6.2

---

docs/user/motors/tanks.rst

The existing documentation for the ``spherical_caps`` parameter currently states:
> The ``spherical_caps`` parameter is optional and defaults to ``False``. If set
> to ``True``, the tank will be defined as a cylinder with flat caps.
> If True, the tank will have spherical caps.
This should be updated to:
> The ``spherical_caps`` parameter is optional and defaults to ``False``. If set
> to ``True``, the tank will have spherical caps at the top and bottom with the
> same radius as the cylindrical part. If set to ``False``, the tank will
> be defined as a cylinder with flat caps.

DOC: fixed documentation about spherical caps

---

CHANGELOG.md
rocketpy/rocket/aero_surface/generic_surface.py
rocketpy/rocket/aero_surface/linear_generic_surface.py
rocketpy/simulation/flight.py

Fixed the calculation of the angle of sideslip to be in accordance with the documentation.
Fixed the sign of the damping coefficient in the `LinearGenericSurface`

BUG: Sideslip Angle and Damping Coefficient Calculation 

---

CHANGELOG.md
rocketpy/stochastic/stochastic_rocket.py

Bugfix
If there is a rocket with 2 sets of fins and you try to make them stochastic, the function that is fixed in the code will throw because it only checks the first set of fins.  This makes it impossible to add 2 sets of fins.
Here is a sample program if you wish to confirm:
```py
from rocketpy import TrapezoidalFins, Rocket, StochasticTrapezoidalFins, StochasticRocket
percentStdDeviation = 0.1
testRocket = Rocket( # All of the data is incorrect
radius=0.1,
mass=1,
inertia=(6.321, 6.321, 0.034),
power_off_drag= "powerOffDragCurve.csv",
power_on_drag= "powerOnDragCurve.csv",
center_of_mass_without_motor=0.5,
coordinate_system_orientation="tail_to_nose",
)
fin_set_1 = testRocket.add_trapezoidal_fins(
n=4,
root_chord=0.203,
tip_chord=0.0381,
span=0.102,
sweep_length=0.21,
position=-0.015, …
```

BUG: Allow multiple sets of stochastic fins

---

CHANGELOG.md
rocketpy/mathutils/function.py
rocketpy/motors/hybrid_motor.py
rocketpy/motors/liquid_motor.py
rocketpy/motors/motor.py
rocketpy/motors/solid_motor.py
rocketpy/motors/tank.py
rocketpy/plots/aero_surface_plots.py
rocketpy/plots/compare/compare_flights.py
rocketpy/plots/environment_analysis_plots.py
rocketpy/plots/environment_plots.py
rocketpy/plots/flight_plots.py
rocketpy/plots/hybrid_motor_plots.py
rocketpy/plots/liquid_motor_plots.py
rocketpy/plots/motor_plots.py
rocketpy/plots/rocket_plots.py
rocketpy/plots/solid_motor_plots.py
rocketpy/plots/tank_plots.py
rocketpy/rocket/aero_surface/fins/fins.py
rocketpy/rocket/aero_surface/nose_cone.py
rocketpy/rocket/rocket.py
rocketpy/utilities.py

As described by the conversation in #731 , this PR moves the `filename` parameter to the end so as to avoid potential future breaking changes.

MNT: Place filename save parameter to the end.

---

CHANGELOG.md
rocketpy/environment/environment.py

Bugfix
If the environment date is updated after setting the atmospheric model, the function call to update the model to that date did not pass ``self.atmospheric_model_type`` when it is required by the function.  This led to the file being passed in as the type.
Behaves as expected
N/A

BUG: Correctly update atmospheric conditions after changing date and location

---

.vscode/settings.json
CHANGELOG.md
rocketpy/simulation/flight.py
tests/integration/test_flight.py

Currently only `LSODA` is used to integrate the equations of motion of the `Flight` class, with no option for other solvers or custom code.
This PR adds the possibility of using different solvers from `scipy.integrate` API.
`LSODA`, of course, remains the default option and the strongly recommended one. Quick testing showed that other solvers might match `LSODA` speed, but require more tuning to avoid instabilities.

ENH: Allow for Alternative and Custom ODE Solvers.

---

.vscode/settings.json
rocketpy/environment/environment.py
rocketpy/environment/fetchers.py
rocketpy/environment/tools.py
rocketpy/mathutils/function.py
rocketpy/mathutils/vector_matrix.py
rocketpy/motors/fluid.py
rocketpy/motors/motor.py
rocketpy/plots/rocket_plots.py
rocketpy/prints/compare_prints.py
rocketpy/rocket/aero_surface/nose_cone.py
rocketpy/rocket/rocket.py
rocketpy/sensitivity/sensitivity_model.py
rocketpy/simulation/flight.py
rocketpy/tools.py
rocketpy/utilities.py
tests/fixtures/flight/flight_fixtures.py
tests/fixtures/surfaces/surface_fixtures.py
tests/integration/test_flight.py
tests/unit/test_aero_surfaces.py
tests/unit/test_flight_time_nodes.py
tests/unit/test_function.py
tests/unit/test_sensitivity.py
tests/unit/test_tank.py
tests/unit/test_tools.py
tests/unit/test_units.py
tests/unit/test_utilities.py

* Coverage without slow tests: 76%
* Coverage without slow tests: 80%
* Coverage with slow tests: 92%
* I'm not sure if I will have time to add more tests, so I guess the PR is ready for review
* Please review carefully the logics behind the tests.

TST: increase test coverage

---

CHANGELOG.md
rocketpy/motors/__init__.py
rocketpy/motors/empty_motor.py
rocketpy/motors/motor.py
rocketpy/rocket/rocket.py
rocketpy/stochastic/stochastic_rocket.py
tests/conftest.py
tests/fixtures/motor/empty_motor_fixtures.py
tests/fixtures/motor/solid_motor_fixtures.py
tests/integration/test_empty_motor.py
tests/unit/test_rocket.py

The EmptyMotor is a huge workaround
The EmptyMotor ihnerits from the abstract Motor class
#778 needs this first

MNT: EmptyMotor class inherits from Motor(ABC)

---

CHANGELOG.md
rocketpy/simulation/flight.py

In the Flight class, during two-stage rocket simulations, the second-stage motor is temporarily turned off after separation (except in hot separation cases). However, the current condition for applying power-on drag (`t < self.rocket.motor.burn_out_time`) incorrectly keeps power-on drag active during this period.
The condition has been updated to `self.rocket.motor.burn_start_time < t < self.rocket.motor.burn_out_time` in `u_dot` and `u_dot_generalized` to ensure proper handling of drag forces for both single- and multi-stage rockets. This ensures that power-off drag is correctly applied when the second-stage motor is off.
Firstly reported here: https://discord.com/channels/765037887016140840/1334492994631372810

BUG: update flight simulation logic to include burn start time

---

CHANGELOG.md
rocketpy/plots/rocket_plots.py

See https://github.com/RocketPy-Team/RocketPy/issues/766,
When calling rocket.all_info() on a "surfaceless rocket", it throw an error.
Now you will see no more errors when trying to print out information from a rocket without aero surfaces.
I tested with the getting started notebook. Everything is looking fine.
Essentially: if you do not define any aerodynamic surface, why in the world would you want to draw the rocket? Sorry but we can't.

Bug: do not allow drawing rockets with no aerodynamic surface

---

CHANGELOG.md
docs/user/motors/thrust.rst
rocketpy/motors/motor.py

Pending documentation building

DOCS: reshape docs (closes #659)

---

CHANGELOG.md
rocketpy/mathutils/function.py
rocketpy/simulation/flight.py
tests/unit/test_utilities.py

When calling the function `get_instance_attributes()` and passing a Flight object that contains a Rocket object without rail buttons as the argument, it crashes. More specifically, it crashes when trying to calculate the rail button forces (`__calculate_rail_button_forces`).
Stack trace:
```self = <rocketpy.mathutils.function.funcify_method.<locals>.funcify_method_decorator object at 0x1112cf4d0>
instance = <Flight(rocket= <rocketpy.rocket.rocket.Rocket object at 0x11370c410>, environment= <rocketpy.environment.environment.Environment object at 0x110e2b680>, rail_length= 5.2, inclination= 85, heading = 0,name= Flight)>
owner = <class 'rocketpy.simulation.flight.Flight'>
def __get__(self, instance, owner=None):
if instance is None:
return self
cache = instance.__dict__
try:
>           val …
```

BUG: fixes get_instance_attributes for Flight objects containing a Rocket object without rail buttons

---

CHANGELOG.md
Makefile

Running `make install` didn't install all packages necessary to develop RocketPy locally, specifically to run the tests. In order to have **ruff** installed, for example, it was necessary to run `pip install -r requirements-tests.txt` separately.
Running `make install` installs all necessary packages to develop and test RocketPy locally.
`make install` was executed in a new, blank virtual environment locally and it successfully installed **ruff**.

DEV: add requirements-tests.txt on make install target

---

CHANGELOG.md
rocketpy/environment/environment.py
rocketpy/environment/fetchers.py
rocketpy/environment/tools.py
rocketpy/plots/rocket_plots.py
rocketpy/rocket/rocket.py
rocketpy/simulation/flight.py
rocketpy/utilities.py

There were some deprecated functions that should have already been removed
Some other deprecated functions were missing the `DeprecationWarning`

DEP: Remove Pending Deprecations and Add Warnings Where Needed

---

CHANGELOG.md
rocketpy/stochastic/stochastic_flight.py

`time_overshoot=None` causes an error in `Flight._simulate`.
Fixes #804 by setting `time_overshoot` to the base flight value when it is `None`. 
Still need to fix `time_overshoot=False` problem described in #802

Bug: Fix StochasticFlight time_overshoot None bug

---

CHANGELOG.md
rocketpy/simulation/flight.py

Note: Non-related `MonteCarlo` tests have failed. I am investigating it.
A bug introduced by yours truly on PR #748 causes the simulation solver not detect correctly when using `LSODA` solver. This is crucial when performing non-overshootable simulations.
This PR fixes the issue by correctly detecting the usage of `LSODA`.
This could have been detected earlier had the `--runslow` tests been executed more often.

BUG: LSODA solver not being detected correctly.

---

CHANGELOG.md
rocketpy/prints/sensors_prints.py
rocketpy/sensors/accelerometer.py
rocketpy/sensors/gyroscope.py
rocketpy/sensors/sensor.py
rocketpy/simulation/flight.py
tests/integration/test_sensor.py
tests/unit/test_sensor.py

Some rotations were wrong in the sensors class:
- The gyroscope receives an angular velocity described in the body frame. There was an extra rotation being made. That was removed since it is not needed
- The accelerometer receives an acceleration vector described in the inertial frame. This vector was then **wrongly**  rotated from body to inertial, when it should be inertial to body. This was fixed by adding a `.transpose`
- Acceleration and velocity attributes described in the body frame were created in the flight class for clarity
I also took the chance to improve/correct some of the docs strings of some Flight attributes

BUG: Unecessary Gyroscope Rotation and Wrong Acceleremoter Rotation

---

CHANGELOG.md
rocketpy/mathutils/function.py
tests/unit/test_function.py

PR #785 introduced the possibility of 2D `Function` multiplication. The intent of this PR is to generalize this to the other arithmetical operations and to ND `Functions` for better scalability (e.g. so as not keep adding if blocks for every dimension, like 3D, 4D etc).
The generalization is done with the following changes:
- Use the `self._domain` and `self._image` for array manipulation, instead of unidimensional `self.x_array` and `self.y_array`;
- Multivariate lambda expressions are generated to allow callable operations:
- The implementation is less trivial, requiring dynamically building a multivariate `lambda`;
- This PR implementation worked very well on testing, but, if it does not hold review scrutinity due the use of `eval`, it can easily be converted into an `exception` and …

ENH: support for ND arithmetical operations for Function.

---

.github/workflows/test_pytest.yaml

Fix the following message:
```text
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```
See updated docs: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

DEV: fix pip cache on github workflow

---

CHANGELOG.md
rocketpy/_encoders.py
rocketpy/environment/environment.py
rocketpy/mathutils/function.py
rocketpy/mathutils/vector_matrix.py
rocketpy/motors/fluid.py
rocketpy/motors/hybrid_motor.py
rocketpy/motors/liquid_motor.py
rocketpy/motors/motor.py
rocketpy/motors/solid_motor.py
rocketpy/motors/tank.py
rocketpy/motors/tank_geometry.py
rocketpy/rocket/aero_surface/fins/elliptical_fins.py
rocketpy/rocket/aero_surface/fins/fins.py
rocketpy/rocket/aero_surface/fins/free_form_fins.py
rocketpy/rocket/aero_surface/fins/trapezoidal_fins.py
rocketpy/rocket/aero_surface/nose_cone.py
rocketpy/rocket/aero_surface/rail_buttons.py
rocketpy/rocket/aero_surface/tail.py
rocketpy/rocket/components.py
rocketpy/rocket/parachute.py
rocketpy/rocket/rocket.py
rocketpy/simulation/flight.py
tests/integration/test_encoding.py

The standard `RocketPyEncoder` currently does not support custom options for users/clients that may have the following needs:
- Discrete encoding: as documented, this is useful to have the `callable` defined `Functions` written out in a human readable format. Of course, this has the drawback that the original `callable` cannot be exactly reproduced on decoding;
- No-Pickle encoding: as it is common on I/O libraries/functions (e.g. [NumPy save](https://numpy.org/doc/2.0/reference/generated/numpy.save.html)) having a toggle for pickling is beneficial for allowing the user/client having better control of security and output size (pickled objects might get large). This specially useful if there is no interest in decoding the result.
The added options `discretize` and `allow_pickle` work as …

ENH: Discretized and No-Pickle Encoding Options
