- nbks/rocketpyAlpha.py
Pull request for:
- Functions are now fully documented in RocketpyAlpha.py (fixes #6) 
- Return behavior of functions is now predictable (fixes #7)
> Complete documentation

- rocketpy/Flight.py
- rocketpy/Rocket.py
This change aims to fix some problems with pull request #36
> Now self.thrustToWeight is defined in class rocket

- rocketpy/Flight.py
There are some warnings generated when using python 3.8 due to [issue34850](https://bugs.python.org/issue34850).
I made some very minor syntax changes to address these warnings.
> Minor changes for py3.8 to comply with issue34850

- docs/conf.py
- docs/requirements.txt
RocketPy's code did not have any unit tests setup.
- 
- 
- 
-
> Add pydata html theme

- README.md
ReadMe does not describe what are the main functionalities of RocketPy.
ReadMe clearly states all main functionalities of RocketPy.
- Nonlinear 6 degrees of freedom simulations
- Solved using LSODA with adjustable error tolerances
- Rigorous treatment of mass variation effects
- Barrowman equations for lift coefficients (optional)
- Parachutes with external trigger functions
- Test the exact code that will fly
- Sensor data can be augmented with noise
- Solid motors models:
- Burn rate and mass variation properties from thrust curve
- Accurate weather modeling
- International Standard Atmosphere (1976)
- Custom atmospheric profiles
- Soundings (Wyoming, NOAARuc)
- Weather …
> Docs/Add functionalities to ReadMe

- Makefile
- requirements_test.txt
- rocketpy/Environment.py
- rocketpy/Flight.py
- rocketpy/Function.py
- tests/test_environment.py
`verify-lint` script always returns error because black --check does not work for intended use
- Modified `verify-lint` script for using flake8 to verify black linter rules
> Workin travis script

- rocketpy/Flight.py
RocketPy's code did not have any unit tests setup.
- Corrected a few typos and incorrect terms on Flight Class documentation
- Part of series of first issues tackled by new dev team to familiarize themselves with the code
> Fixed typos on Flight class docs

- README.md
RocketPy has few and outdated badges!
New badges were added:
- Build passing
- LinkedIn
- PyPI version
- Paper DOI
- Number of contributors
The MyBinder badge has been removed.
> ReadMe has got new badges!

- rocketpy/Environment.py
One acceptance test fails after `date2index` behavior change in the newest version of `cftime` (a library used by netCDF4). Check https://github.com/Unidata/cftime/pull/273 and https://github.com/Unidata/netcdf4-python/issues/1155 for more details.
I rolled back a change I made to remove a warning during tests. With the bug fixed in the new `cftime` version, our original implementation works once again.
This PR is really simple, just changed 2 words. At the same time, it fixes a test which is currently failing. Therefore, I hope we can review and accept it fast. @Gui-FernandesBR, can you …
> ENH: adapt to new cftime version

- rocketpy/EnvironmentAnalysis.py
Implementation of wind related calculations.
> ENH: Environment Analysis - Wind Related Calculations

- rocketpy/EnvironmentAnalysis.py
A complete set of wind roses can only be seen in an animation created by `EnviornmentAnalysis.animate_average_wind_rose`.
`EnvironmentAnalysis.plot_average_wind_rose_all_hours` method can generate a grid of wind roses as shown below. The number of rows and columns is automatically calculated by the `EnvironmentAnalysis._find_two_closest_integer_factors` method.
> ENH: Environment Analysis - Animations to Grids

- rocketpy/EnvironmentAnalysis.py
> ENH: Environment Analysis - Allowing for meter to feet conversion

- rocketpy/EnvironmentAnalysis.py
Currently, the wind profile over an average day can only be seen through an animation. Thus, it is hard to analyze the average wind profile at a specific time of the day.
The average wind profile for each available hour can now be plotted in a grid.
> ENH: Enviroment Analysis - Animation to Grids - Wind Profile

- rocketpy/EnvironmentAnalysis.py
Reverts Projeto-Jupiter/RocketPy#176
> Revert "ENH: Environment Analysis - Units"

- rocketpy/Environment.py
In the description of the decimalDegreeToArcSeconds method in the class Environment the 
description of arc seconds is (1/360)/*degree
Now the new description of arc seconds is (1/3600)/*degree
> MAINT: fix arcsec definition in docs

- rocketpy/EnvironmentAnalysis.py
- Elevation must be given by user when initializing the `Environment Analysis` class.
- Elevation is not converted to the desired units and unit system is chosen or changed. Therefore, it must be entered in the correct units.
- All profile plots are a function of Altitude Above Sea Level (ASL), while Altitude Above Ground Level (AGL) is preferred.
- Elevation is now computed automatically from the surface data source file.
- Elevation is correctly converted to the desired unit system, both on initialization and on change.
- All profile …
> ENH: Environment Analysis - Auto Elevation and ASL to AGL

- rocketpy/EnvironmentAnalysis.py
- There are no surface wind speed plots
- There are no indication of SAcup altitude or wind speed constraint on the plots
- Methods for plotting average surface wind speed along the day and average wind speed at 100m height along the day have been added
- Added methods call to [docs/notebooks/environment_analysis_class_usage.ipynb](https://github.com/Projeto-Jupiter/RocketPy/pull/192/files#diff-57b57c4118e4de914325b84755a78cca211ca4bf40bcf3c8744e21be1253d3b6)
- Optional argument for plotting methods that, if set to True, show SAcup constraints on allowed apogee and wind speed value at launch on the …
> Added wind speed at surface calculations and SAcup rules constraints lines to some plots

- docs/requirements.txt
- docs/user/requirements.rst
Due to a weird ReadTheDocs bug, it was not being able to install the latest version of some libraries from PYPI, because they are relatively recently.
Since the most recent versions of these libraries were not really necessary, I dropped their requirements. I have also updated the Requirements page of the documentation to reflect this library changes.
This PR modifies only the documentation being built online by ReadTheDocs. Therefore, no new package release is needed.
Furthermore, I have confirmed that the current solution works, as shown by the successfull build of this branch`s docs in ReadTheDocs: …
> FIX: fixing docs error - 2nd attempt

- .github/FUNDING.yml
Now adding a new Sponsors Button on our main page
In the future we probably may publish sponsors logos here
> MAINT: Create FUNDING.yml

- README.md
Now we have a new badge on our README, and it is the github sponsors badge!
> MAINT: Adding Github Sponsors badge to README

- rocketpy/Rocket.py
- rocketpy/plots/rocket_plots.py
> ENH: Moved Rocket plots to rocket_plots.py

- rocketpy/AeroSurfaces.py
- rocketpy/Rocket.py
- rocketpy/prints/rocket_prints.py
> ENH: Moved Rocket prints to rocket_prints.py

- README.md
- [ X ] ReadMe, Docs and GitHub maintenance
- [ X ] Spelling has been verified
- [ X ] Code docs are working correctly 
addTrapezoildalFins was incorrectly spelled in the docs, leading to issues for whoever is copy-pasting the example.
addTrapezoildalFins changed to addTrapezoidalFins
- [ X ] No
> changes addTrapezoildalFins to addTrapezoidalFins

- rocketpy/Flight.py
Four issues are being solved (each one is a different commits):
1 - When using initialSolution, the time array gets a mismatch with other properties. This is a very small issue that can annoy sometimes. Not pulling into develop since it is minor.
2 - Simulation only runs when a set of rail button is added, I'm changing it. In the future we probably will need to better discuss the role of "effectiveRailXX" attributes.
3 - Extracting two initialization methods from the 
4 - Allow Flight objected being passed as arguments to initial solution; 
I'm bringing by cherry-pick from #243 PR, which …
> MAINT: refactor flight class __init__ method

- rocketpy/AeroSurfaces.py
- rocketpy/EnvironmentAnalysis.py
- rocketpy/Function.py
- tests/fixtures/acceptance/EPFL_Bella_Lui/bella_lui_flight_sim.py
- tests/fixtures/acceptance/NDRT_2020/ndrt_2020_flight_sim.py
See #331.
Issue #331 is fixed by implementing a correct analytical integral of linearly interpolated Functions.
Refactoring the Flight class is long overdue... I am not comfortable with the size (number of lines of code) of the integral method, but creating "sub" functions goes against the current organization of the Function class.
> FIX: Implementation of analytical integral of linearly interpolated Functions

- rocketpy/Function.py
Added a Piecewise Function to to Function.py. (It takes in a dictionary where the keys are the domain and the values are the Functions and returns a Function object). There are also updates to Function.differentiate. The methods derivativeFunction (returns a Function that is the derivative of the original), integralFunction (returns a Function that is the integral of the original), invert (returns a function whose domain is now the range and the range is now the domain), …
> Added Piecewise class and other new Function methods

- tests/test_utilities.py
Co-authored-by: MateusStano <69485049+MateusStano@users.noreply.github.com>
Co-authored-by: phmbressan <69485049+phmbressan@users.noreply.github.com>
`test_fin_flutter_analysis` fails value assertions, with different values on each PC, due to different LSODA iterations on each.
- Assertion tolerance has been drastically decreased to 1e-3, instead of 1e-6.
- Increasing time steps, and making integration tolerances tighter helped decrease errors, but made execution time not viable.
> TST: Flutter test fix

- rocketpy/Flight.py
- tests/test_utilities.py
Yup... this is the sadest PR ever...
> Fix: Flight Reynolds & Dynamic viscosity wrong values

- rocketpy/Function.py
> BUG: `*` instead of `-` in __sub__

- rocketpy/AeroSurface.py
- rocketpy/Environment.py
- rocketpy/EnvironmentAnalysis.py
- rocketpy/Flight.py
- rocketpy/Function.py
- rocketpy/Parachute.py
- rocketpy/Rocket.py
- rocketpy/motors/HybridMotor.py
- rocketpy/motors/LiquidMotor.py
- rocketpy/motors/Motor.py
- rocketpy/motors/SolidMotor.py
- rocketpy/motors/Tank.py
- rocketpy/motors/TankGeometry.py
- rocketpy/plots/aero_surface_plots.py
- rocketpy/plots/environment_plots.py
- rocketpy/plots/flight_plots.py
- rocketpy/plots/hybrid_motor_plots.py
- rocketpy/plots/solid_motor_plots.py
- rocketpy/prints/flight_prints.py
- rocketpy/prints/hybrid_motor_prints.py
- rocketpy/prints/solid_motor_prints.py
- rocketpy/utilities.py
- tests/test_solidmotor.py
The `u_dot_generalized` method was not included in the snake_case PR, so it was missing the correct formatting.
This was causing an issue in simulations with Roll, because the roll moment `M3` was not being calculated at all due to it being inside an exception.
> BUG: Snake Case Review

- .github/pull_request_template.md
Hey! The old PR template was a little too long and annoyed me a bit. Here is a suggestion of a simpler version, you can see the template below. Just a quick change to improve quality of life.
---
> DEV: New PR Template

- docs/conf.py
- docs/user/installation.rst
- setup.py
Update `setup` versioning to `v1.0.1`.
> REL: bump versioning to v1.0.1.

- CODEOWNERS
I am the only code-owner.
The team @RocketPy-Team/code-owners is the new code owner.
See https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> GIT: Set code owners as @RocketPy-Team/code-owners

- CHANGELOG.md
- docs/conf.py
- docs/user/installation.rst
- setup.py
Updating to the next version, more than 302 commits are going to be included in this next release.
> REL: Update version to 1.2.0

- CHANGELOG.md
- docs/conf.py
- docs/user/installation.rst
- setup.py
> REL: Update version to 1.2.2

- CHANGELOG.md
- docs/conf.py
- docs/user/installation.rst
- pyproject.toml
Bumps rocketpy version to 1.4.0
> REL: v1.4.0

- CHANGELOG.md
- docs/conf.py
- docs/user/installation.rst
- pyproject.toml
- rocketpy/rocket/aero_surface/rail_buttons.py
- rocketpy/rocket/rocket.py
- rocketpy/simulation/flight.py
- tests/unit/test_rocket.py
Minor version to solve bugs and fix small things.
> REL: Bump versioning to RocketPy v1.4.2

- CHANGELOG.md
- docs/conf.py
- docs/user/installation.rst
- pyproject.toml
> REL: Bump versioning to RocketPy v1.4.3.

- docs/conf.py
- docs/examples/cavour_flight_sim.ipynb
- docs/examples/halcyon_flight_sim.ipynb
- docs/examples/index.rst
- docs/reference/classes/sensors/abstract/sensor.rst
- docs/reference/classes/sensors/accelerometer.rst
- docs/reference/index.rst
- docs/user/rocket/generic_surface.rst
- rocketpy/rocket/rocket.py
- rocketpy/sensors/accelerometer.py
- rocketpy/sensors/barometer.py
- rocketpy/sensors/gnss_receiver.py
- rocketpy/sensors/gyroscope.py
- rocketpy/sensors/sensor.py
Fixed a few errors from what I saw on readthedocs, and also added the following picture:
> DOC: new comparison plot

- README.md
Quick and easy approval
I want to close #525 
preview:
> DOC: Updates README

- CHANGELOG.md
- docs/conf.py
- docs/user/installation.rst
- pyproject.toml
> REL: update version to 1.7.1 in configuration files.

- CHANGELOG.md
- docs/examples/camoes_flight_sim.ipynb
- docs/examples/defiance_flight_sim.ipynb
- docs/examples/index.rst
- docs/requirements.in
- docs/requirements.txt
Matplotlib is great, but plotly... Well, plotly is a masterpiece!
When hovering...
@phmbressan could you pip compile the docs/requirements.txt this again please? I would not like cloning the repo to linux again.
> DOC: flight comparison improvements
